name: "tanka"
version: "0.0.2"
description: "Provide Tanka support to Helm"
usage: |-
  This plugin provides integration with the Tanka project.

  It provides Tanka integration with Helm, generating Helm
  templates from jsonnet source.
command: "$HELM_PLUGIN_DIR/tanka.sh"
